








































#ifndef _CCAPI_TYPES_H_
#define _CCAPI_TYPES_H_

#include "cc_constants.h"




typedef unsigned int cc_device_handle_t;



typedef const char *file_path_t;



typedef struct cc_device_info_t_* cc_deviceinfo_ref_t;



typedef struct cc_line_info_t_ * cc_lineinfo_ref_t;



typedef struct cc_feature_info_t_ * cc_featureinfo_ref_t;



typedef struct cc_call_info_t_* cc_callinfo_ref_t;



typedef struct cc_call_server_t_* cc_callserver_ref_t;




typedef struct cc_call_log_t_* cc_calllog_ref_t;

#define CCAPI_MAX_SERVERS 4



typedef enum {
  CCAPI_CALL_EV_CREATED,
  CCAPI_CALL_EV_STATE,
  CCAPI_CALL_EV_CALLINFO,
  CCAPI_CALL_EV_ATTR,
  CCAPI_CALL_EV_SECURITY,
  CCAPI_CALL_EV_LOG_DISP,
  CCAPI_CALL_EV_PLACED_CALLINFO,
  CCAPI_CALL_EV_STATUS,
  CCAPI_CALL_EV_SELECT,
  CCAPI_CALL_EV_LAST_DIGIT_DELETED,
  CCAPI_CALL_EV_GCID,
  CCAPI_CALL_EV_XFR_OR_CNF_CANCELLED,
  CCAPI_CALL_EV_PRESERVATION,
  CCAPI_CALL_EV_CAPABILITY,
  CCAPI_CALL_EV_VIDEO_AVAIL,
  CCAPI_CALL_EV_VIDEO_OFFERED,
  CCAPI_CALL_EV_RECEIVED_INFO,
  CCAPI_CALL_EV_RINGER_STATE,
  CCAPI_CALL_EV_CONF_PARTICIPANT_INFO,
  CCAPI_CALL_EV_MEDIA_INTERFACE_UPDATE_BEGIN,
  CCAPI_CALL_EV_MEDIA_INTERFACE_UPDATE_SUCCESSFUL,
  CCAPI_CALL_EV_MEDIA_INTERFACE_UPDATE_FAIL
} ccapi_call_event_e;




typedef enum {
  CCAPI_LINE_EV_CONFIG_CHANGED,
  CCAPI_LINE_EV_REG_STATE,
  CCAPI_LINE_EV_CAPSET_CHANGED,
  CCAPI_LINE_EV_CFWDALL,
  CCAPI_LINE_EV_MWI
} ccapi_line_event_e;




typedef enum {
  CCAPI_DEVICE_EV_CONFIG_CHANGED,
  CCAPI_DEVICE_EV_STATE, 
  CCAPI_DEVICE_EV_IDLE_SET,
  CCAPI_DEVICE_EV_MWI_LAMP,
  CCAPI_DEVICE_EV_NOTIFYPROMPT,
  CCAPI_DEVICE_EV_SERVER_STATUS,
  CCAPI_DEVICE_EV_BLF,
  CCAPI_DEVICE_EV_CAMERA_ADMIN_CONFIG_CHANGED,
  CCAPI_DEVICE_EV_VIDEO_CAP_ADMIN_CONFIG_CHANGED
} ccapi_device_event_e;




typedef enum {
  CCAPI_CALL_CAP_NEWCALL,
  CCAPI_CALL_CAP_ANSWER,
  CCAPI_CALL_CAP_ENDCALL,
  CCAPI_CALL_CAP_HOLD,
  CCAPI_CALL_CAP_RESUME,
  CCAPI_CALL_CAP_CALLFWD,
  CCAPI_CALL_CAP_DIAL,
  CCAPI_CALL_CAP_BACKSPACE,
  CCAPI_CALL_CAP_SENDDIGIT,
  CCAPI_CALL_CAP_TRANSFER,
  CCAPI_CALL_CAP_CONFERENCE,
  CCAPI_CALL_CAP_SWAP,
  CCAPI_CALL_CAP_BARGE,
  CCAPI_CALL_CAP_REDIAL,
  CCAPI_CALL_CAP_JOIN,
  CCAPI_CALL_CAP_SELECT,
  CCAPI_CALL_CAP_RMVLASTPARTICIPANT,
  CCAPI_CALL_CAP_MAX
} ccapi_call_capability_e;

#endif 
