---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/job_flags.yml

$inherits:
  from: tasks/branches/mozilla-central/job_flags.yml

builds:
  flame-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml
  aries-nightly:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_lightsaber_nightly.yml

tests:
  gaia-build:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_opt.yml:
        task: tasks/tests/b2g_build_test.yml
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_build_test.yml
  gaia-linter:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_opt.yml:
        task: tasks/tests/b2g_linter.yml
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_linter.yml

