



import sys
import string

propList = eval(sys.stdin.read())
props = ""
for [name, prop, id, flags, pref] in propList:
    extendedAttrs = ["Throws", "TreatNullAs=EmptyString"]
    
    
    
    
    
    if "CSS_PROPERTY_ALWAYS_ENABLED_IN_CHROME_OR_CERTIFIED_APP" in flags:
        extendedAttrs.append('Func="IsCSSPropertyExposedToJS<eCSSProperty_%s>"' % id)
    
    
    elif pref is not "":
        extendedAttrs.append('Pref="%s"' % pref)
    if not prop.startswith("Moz"):
        prop = prop[0].lower() + prop[1:]
    
    
    props += "  [%s] attribute DOMString %s;\n" % (", ".join(extendedAttrs),
                                                   prop)

idlFile = open(sys.argv[1], "r");
idlTemplate = idlFile.read();
idlFile.close();

print ("/* THIS IS AN AUTOGENERATED FILE.  DO NOT EDIT */\n\n" +
       string.Template(idlTemplate).substitute({ "props": props }))
