








































#include "OLEACC.H"
#include "AccessibleRole.h"

const PRUint32 USE_ROLE_STRING = 0;
const PRUint32 ROLE_WINDOWS_LAST_ENTRY = 0xffffffff;

#ifndef ROLE_SYSTEM_SPLITBUTTON
const PRUint32 ROLE_SYSTEM_SPLITBUTTON  = 0x3e; 
#endif

#ifndef ROLE_SYSTEM_IPADDRESS
const PRUint32 ROLE_SYSTEM_IPADDRESS = 0x3f; 
#endif

#ifndef ROLE_SYSTEM_OUTLINEBUTTON
const PRUint32 ROLE_SYSTEM_OUTLINEBUTTON = 0x40; 
#endif

struct WindowsRoleMapItem
{
  PRUint32 msaaRole;
  long ia2Role;
};


static const WindowsRoleMapItem gWindowsRoleMap[] = {
  
  { USE_ROLE_STRING, IA2_ROLE_UNKNOWN },

  
  { ROLE_SYSTEM_TITLEBAR, ROLE_SYSTEM_TITLEBAR },

  
  { ROLE_SYSTEM_MENUBAR, ROLE_SYSTEM_MENUBAR },

  
  { ROLE_SYSTEM_SCROLLBAR, ROLE_SYSTEM_SCROLLBAR },

  
  { ROLE_SYSTEM_GRIP, ROLE_SYSTEM_GRIP },

  
  { ROLE_SYSTEM_SOUND, ROLE_SYSTEM_SOUND },

  
  { ROLE_SYSTEM_CURSOR, ROLE_SYSTEM_CURSOR },

  
  { ROLE_SYSTEM_CARET, ROLE_SYSTEM_CARET },

  
  { ROLE_SYSTEM_ALERT, ROLE_SYSTEM_ALERT },

  
  { ROLE_SYSTEM_WINDOW, ROLE_SYSTEM_WINDOW },

  
  { USE_ROLE_STRING, IA2_ROLE_INTERNAL_FRAME},

  
  { ROLE_SYSTEM_MENUPOPUP, ROLE_SYSTEM_MENUPOPUP },

  
  { ROLE_SYSTEM_MENUITEM, ROLE_SYSTEM_MENUITEM },

  
  { ROLE_SYSTEM_TOOLTIP, ROLE_SYSTEM_TOOLTIP },

  
  { ROLE_SYSTEM_APPLICATION, ROLE_SYSTEM_APPLICATION },

  
  { ROLE_SYSTEM_DOCUMENT, ROLE_SYSTEM_DOCUMENT },

  
  
  
  
  
  
  
  { ROLE_SYSTEM_GROUPING , ROLE_SYSTEM_GROUPING }, 

  
  { ROLE_SYSTEM_CHART, ROLE_SYSTEM_CHART },

  
  { ROLE_SYSTEM_DIALOG, ROLE_SYSTEM_DIALOG },

  
  { ROLE_SYSTEM_BORDER, ROLE_SYSTEM_BORDER },

  
  { ROLE_SYSTEM_GROUPING, ROLE_SYSTEM_GROUPING },

  
  { ROLE_SYSTEM_SEPARATOR, ROLE_SYSTEM_SEPARATOR },

  
  { ROLE_SYSTEM_TOOLBAR, ROLE_SYSTEM_TOOLBAR },

  
  { ROLE_SYSTEM_STATUSBAR, ROLE_SYSTEM_STATUSBAR },

  
  { ROLE_SYSTEM_TABLE, ROLE_SYSTEM_TABLE },

  
  { ROLE_SYSTEM_COLUMNHEADER, ROLE_SYSTEM_COLUMNHEADER },

  
  { ROLE_SYSTEM_ROWHEADER, ROLE_SYSTEM_ROWHEADER },

  
  { ROLE_SYSTEM_COLUMN, ROLE_SYSTEM_COLUMN },

  
  { ROLE_SYSTEM_ROW, ROLE_SYSTEM_ROW },

  
  { ROLE_SYSTEM_CELL, ROLE_SYSTEM_CELL },

  
  { ROLE_SYSTEM_LINK, ROLE_SYSTEM_LINK },

  
  { ROLE_SYSTEM_HELPBALLOON, ROLE_SYSTEM_HELPBALLOON },

  
  { ROLE_SYSTEM_CHARACTER, ROLE_SYSTEM_CHARACTER },

  
  { ROLE_SYSTEM_LIST, ROLE_SYSTEM_LIST },

  
  { ROLE_SYSTEM_LISTITEM, ROLE_SYSTEM_LISTITEM },

  
  { ROLE_SYSTEM_OUTLINE, ROLE_SYSTEM_OUTLINE },

  
  { ROLE_SYSTEM_OUTLINEITEM, ROLE_SYSTEM_OUTLINEITEM },

  
  { ROLE_SYSTEM_PAGETAB, ROLE_SYSTEM_PAGETAB },

  
  { ROLE_SYSTEM_PROPERTYPAGE, ROLE_SYSTEM_PROPERTYPAGE },

  
  { ROLE_SYSTEM_INDICATOR, ROLE_SYSTEM_INDICATOR },

  
  { ROLE_SYSTEM_GRAPHIC, ROLE_SYSTEM_GRAPHIC },

  
  { ROLE_SYSTEM_STATICTEXT, ROLE_SYSTEM_STATICTEXT },

  
  { ROLE_SYSTEM_TEXT, ROLE_SYSTEM_TEXT },

  
  { ROLE_SYSTEM_PUSHBUTTON, ROLE_SYSTEM_PUSHBUTTON },

  
  { ROLE_SYSTEM_CHECKBUTTON, ROLE_SYSTEM_CHECKBUTTON },

  
  { ROLE_SYSTEM_RADIOBUTTON, ROLE_SYSTEM_RADIOBUTTON },

  
  { ROLE_SYSTEM_COMBOBOX, ROLE_SYSTEM_COMBOBOX },

  
  { ROLE_SYSTEM_DROPLIST, ROLE_SYSTEM_DROPLIST },

  
  { ROLE_SYSTEM_PROGRESSBAR, ROLE_SYSTEM_PROGRESSBAR },

  
  { ROLE_SYSTEM_DIAL, ROLE_SYSTEM_DIAL },

  
  { ROLE_SYSTEM_HOTKEYFIELD, ROLE_SYSTEM_HOTKEYFIELD },

  
  { ROLE_SYSTEM_SLIDER, ROLE_SYSTEM_SLIDER },

  
  { ROLE_SYSTEM_SPINBUTTON, ROLE_SYSTEM_SPINBUTTON },

  
  { ROLE_SYSTEM_DIAGRAM, ROLE_SYSTEM_DIAGRAM },

  
  { ROLE_SYSTEM_ANIMATION, ROLE_SYSTEM_ANIMATION },

  
  { ROLE_SYSTEM_EQUATION, ROLE_SYSTEM_EQUATION },

  
  { ROLE_SYSTEM_BUTTONDROPDOWN, ROLE_SYSTEM_BUTTONDROPDOWN },

  
  { ROLE_SYSTEM_BUTTONMENU, ROLE_SYSTEM_BUTTONMENU },

  
  { ROLE_SYSTEM_BUTTONDROPDOWNGRID, ROLE_SYSTEM_BUTTONDROPDOWNGRID },

  
  { ROLE_SYSTEM_WHITESPACE, ROLE_SYSTEM_WHITESPACE },

  
  { ROLE_SYSTEM_PAGETABLIST, ROLE_SYSTEM_PAGETABLIST },

  
  { ROLE_SYSTEM_CLOCK, ROLE_SYSTEM_CLOCK },

  
  { ROLE_SYSTEM_SPLITBUTTON, ROLE_SYSTEM_SPLITBUTTON },

  
  { ROLE_SYSTEM_IPADDRESS, ROLE_SYSTEM_IPADDRESS },

  
  

  
  { ROLE_SYSTEM_STATICTEXT, ROLE_SYSTEM_STATICTEXT },

  
  { ROLE_SYSTEM_INDICATOR, ROLE_SYSTEM_INDICATOR },

  
  { USE_ROLE_STRING, IA2_ROLE_CANVAS },

  
  { ROLE_SYSTEM_MENUITEM, IA2_ROLE_CHECK_MENU_ITEM },

  
  { ROLE_SYSTEM_DIALOG, IA2_ROLE_COLOR_CHOOSER },

  
  { USE_ROLE_STRING, IA2_ROLE_DATE_EDITOR },

  
  { USE_ROLE_STRING, IA2_ROLE_DESKTOP_ICON },

  
  { USE_ROLE_STRING, IA2_ROLE_DESKTOP_PANE },

  
  { USE_ROLE_STRING, IA2_ROLE_DIRECTORY_PANE },

  
  { USE_ROLE_STRING, IA2_ROLE_FILE_CHOOSER },

  
  { USE_ROLE_STRING, IA2_ROLE_FONT_CHOOSER },

  
  { ROLE_SYSTEM_APPLICATION, IA2_ROLE_FRAME },

  
  { USE_ROLE_STRING, IA2_ROLE_GLASS_PANE },

  
  { USE_ROLE_STRING, IA2_ROLE_UNKNOWN },

  
  { ROLE_SYSTEM_PUSHBUTTON, IA2_ROLE_ICON },

  
  { ROLE_SYSTEM_STATICTEXT, IA2_ROLE_LABEL },

  
  { USE_ROLE_STRING, IA2_ROLE_LAYERED_PANE },

  
  { USE_ROLE_STRING, IA2_ROLE_OPTION_PANE },

  
  { ROLE_SYSTEM_TEXT, ROLE_SYSTEM_TEXT },

  
  { ROLE_SYSTEM_MENUPOPUP, ROLE_SYSTEM_MENUPOPUP },

  
  { ROLE_SYSTEM_MENUITEM, IA2_ROLE_RADIO_MENU_ITEM },

  
  { USE_ROLE_STRING, IA2_ROLE_ROOT_PANE },

  
  { USE_ROLE_STRING, IA2_ROLE_SCROLL_PANE },

  
  { USE_ROLE_STRING, IA2_ROLE_SPLIT_PANE },

  
  { ROLE_SYSTEM_COLUMNHEADER, ROLE_SYSTEM_COLUMNHEADER },

  
  { ROLE_SYSTEM_ROWHEADER, ROLE_SYSTEM_ROWHEADER },

  
  { ROLE_SYSTEM_MENUITEM, IA2_ROLE_TEAR_OFF_MENU },

  
  { USE_ROLE_STRING, IA2_ROLE_TERMINAL },

  
  { USE_ROLE_STRING, IA2_ROLE_TEXT_FRAME },

  
  { ROLE_SYSTEM_PUSHBUTTON, IA2_ROLE_TOGGLE_BUTTON },

  
  { ROLE_SYSTEM_OUTLINE, ROLE_SYSTEM_OUTLINE },

  
  { ROLE_SYSTEM_PANE, IA2_ROLE_VIEW_PORT },

  
  { USE_ROLE_STRING, IA2_ROLE_HEADER },

  
  { USE_ROLE_STRING, IA2_ROLE_FOOTER },

  
  { USE_ROLE_STRING, IA2_ROLE_PARAGRAPH },

  
  { USE_ROLE_STRING, IA2_ROLE_RULER },

  
  { ROLE_SYSTEM_COMBOBOX, ROLE_SYSTEM_COMBOBOX },

  
  { ROLE_SYSTEM_TEXT, IA2_ROLE_EDITBAR },

  
  { ROLE_SYSTEM_TEXT, ROLE_SYSTEM_TEXT },

  
  { USE_ROLE_STRING, IA2_ROLE_CAPTION },

  
  { USE_ROLE_STRING, IA2_ROLE_UNKNOWN },

  
  { USE_ROLE_STRING, IA2_ROLE_HEADING },

  
  { USE_ROLE_STRING, IA2_ROLE_PAGE },

  
  { USE_ROLE_STRING, IA2_ROLE_SECTION },

  
  { USE_ROLE_STRING, IA2_ROLE_REDUNDANT_OBJECT },

  
  { USE_ROLE_STRING, IA2_ROLE_FORM },

  
  { USE_ROLE_STRING, IA2_ROLE_INPUT_METHOD_WINDOW },

  
  { ROLE_SYSTEM_APPLICATION, ROLE_SYSTEM_APPLICATION },

  
  { ROLE_SYSTEM_MENUITEM, ROLE_SYSTEM_MENUITEM },

  
  { ROLE_SYSTEM_CLIENT, ROLE_SYSTEM_CLIENT },

  
  { ROLE_SYSTEM_LIST, ROLE_SYSTEM_LIST },

  
  { ROLE_SYSTEM_LISTITEM, ROLE_SYSTEM_LISTITEM },

  
  { ROLE_SYSTEM_GRAPHIC, ROLE_SYSTEM_GRAPHIC },

  
  { ROLE_SYSTEM_LISTITEM, ROLE_SYSTEM_LISTITEM },
  
  
  { ROLE_SYSTEM_LISTITEM, ROLE_SYSTEM_LISTITEM },
  
  
  { ROLE_SYSTEM_LIST, ROLE_SYSTEM_LIST },
  
  
  { ROLE_SYSTEM_EQUATION, ROLE_SYSTEM_EQUATION },
  
  
  { ROLE_SYSTEM_CELL, ROLE_SYSTEM_CELL },

  
  { USE_ROLE_STRING, IA2_ROLE_EMBEDDED_OBJECT },

  
  { ROLE_WINDOWS_LAST_ENTRY, ROLE_WINDOWS_LAST_ENTRY }
};

