---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/job_flags.yml

$inherits:
  from: tasks/branches/base_jobs.yml

builds:
  aries-blobfree:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_opt_blobfree.yml
      debug:
        task: tasks/builds/b2g_aries_spark_debug_blobfree.yml
  aries-dogfood:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_dogfood.yml
  aries-eng-blobfree:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_eng_blobfree.yml
  aries-ota:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_ota_opt.yml
      debug:
        task: tasks/builds/b2g_aries_spark_ota_debug.yml
  flame-kk-blobfree:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt_blobfree.yml
      debug:
        task: tasks/builds/b2g_flame_kk_debug_blobfree.yml
  flame-kk-eng-blobfree:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng_blobfree.yml
  flame-kk-ota:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_ota_opt.yml
      debug:
        task: tasks/builds/b2g_flame_kk_ota_debug.yml
