

















































#define SUPPORTS_NONE 0
#define SUPPORTS_LANG 1
#define SUPPORTS_TEST 2
#define SUPPORTS_EXTERNAL 4
#define SUPPORTS_ALL 7

SVG_ELEMENT(a, SUPPORTS_LANG|SUPPORTS_TEST)
SVG_ELEMENT(altGlyph, SUPPORTS_ALL)
SVG_ELEMENT(altGlyphDef, SUPPORTS_NONE)
SVG_ELEMENT(altGlyphItem, SUPPORTS_NONE)
SVG_ELEMENT(animate, SUPPORTS_EXTERNAL|SUPPORTS_TEST)
SVG_ELEMENT(animateColor, SUPPORTS_EXTERNAL|SUPPORTS_TEST)
SVG_ELEMENT(animateMotion, SUPPORTS_EXTERNAL|SUPPORTS_TEST)
SVG_ELEMENT(animateTransform, SUPPORTS_EXTERNAL|SUPPORTS_TEST)
SVG_ELEMENT(circle, SUPPORTS_ALL)
SVG_ELEMENT(clipPath, SUPPORTS_ALL)
SVG_ELEMENT(colorProfile, SUPPORTS_NONE)
SVG_ELEMENT(cursor, SUPPORTS_ALL)
SVG_ELEMENT(definition_src, SUPPORTS_NONE)
SVG_ELEMENT(defs, SUPPORTS_ALL)
SVG_ELEMENT(desc, SUPPORTS_LANG)
SVG_ELEMENT(ellipse, SUPPORTS_ALL)
SVG_ELEMENT(feBlend, SUPPORTS_NONE)
SVG_ELEMENT(feColorMatrix, SUPPORTS_NONE)
SVG_ELEMENT(feComponentTransfer, SUPPORTS_NONE)
SVG_ELEMENT(feComposite, SUPPORTS_NONE)
SVG_ELEMENT(feConvolveMatrix, SUPPORTS_NONE)
SVG_ELEMENT(feDiffuseLighting, SUPPORTS_NONE)
SVG_ELEMENT(feDisplacementMap, SUPPORTS_NONE)
SVG_ELEMENT(feDistantLight, SUPPORTS_NONE)
SVG_ELEMENT(feFlood, SUPPORTS_NONE)
SVG_ELEMENT(feFuncR, SUPPORTS_NONE)
SVG_ELEMENT(feFuncG, SUPPORTS_NONE)
SVG_ELEMENT(feFuncB, SUPPORTS_NONE)
SVG_ELEMENT(feFuncA, SUPPORTS_NONE)
SVG_ELEMENT(feGaussianBlur, SUPPORTS_NONE)
SVG_ELEMENT(feImage, SUPPORTS_EXTERNAL|SUPPORTS_LANG)
SVG_ELEMENT(feMerge, SUPPORTS_NONE)
SVG_ELEMENT(feMergeNode, SUPPORTS_NONE)
SVG_ELEMENT(feMorphology, SUPPORTS_NONE)
SVG_ELEMENT(feOffset, SUPPORTS_NONE)
SVG_ELEMENT(fePointLight, SUPPORTS_NONE)
SVG_ELEMENT(feSpecularLighting, SUPPORTS_NONE)
SVG_ELEMENT(feSpotLight, SUPPORTS_NONE)
SVG_ELEMENT(feTile, SUPPORTS_NONE)
SVG_ELEMENT(feTurbulence, SUPPORTS_NONE)
SVG_ELEMENT(filter, SUPPORTS_LANG|SUPPORTS_EXTERNAL)
SVG_ELEMENT(font, SUPPORTS_EXTERNAL)
SVG_ELEMENT(font_face, SUPPORTS_NONE)
SVG_ELEMENT(font_face_format, SUPPORTS_NONE)
SVG_ELEMENT(font_face_name, SUPPORTS_NONE)
SVG_ELEMENT(font_face_src, SUPPORTS_NONE)
SVG_ELEMENT(font_face_uri, SUPPORTS_NONE)
#ifdef MOZ_SVG_FOREIGNOBJECT
SVG_ELEMENT(foreignObject, SUPPORTS_ALL)
#endif
SVG_ELEMENT(g, SUPPORTS_ALL)
SVG_ELEMENT(glyph, SUPPORTS_NONE)
SVG_ELEMENT(glyphRef, SUPPORTS_NONE)
SVG_ELEMENT(hkern, SUPPORTS_NONE)
SVG_ELEMENT(image, SUPPORTS_ALL)
SVG_ELEMENT(line, SUPPORTS_ALL)
SVG_ELEMENT(linearGradient, SUPPORTS_EXTERNAL)
SVG_ELEMENT(marker, SUPPORTS_EXTERNAL|SUPPORTS_LANG)
SVG_ELEMENT(mask, SUPPORTS_ALL)
SVG_ELEMENT(metadata, SUPPORTS_NONE)
SVG_ELEMENT(missingGlyph, SUPPORTS_NONE)
SVG_ELEMENT(mpath, SUPPORTS_EXTERNAL)
SVG_ELEMENT(path, SUPPORTS_ALL)
SVG_ELEMENT(pattern, SUPPORTS_ALL)
SVG_ELEMENT(polygon, SUPPORTS_ALL)
SVG_ELEMENT(polyline, SUPPORTS_ALL)
SVG_ELEMENT(radialGradient, SUPPORTS_EXTERNAL)
SVG_ELEMENT(rect, SUPPORTS_ALL)
SVG_ELEMENT(script, SUPPORTS_EXTERNAL)
SVG_ELEMENT(set, SUPPORTS_TEST|SUPPORTS_EXTERNAL)
SVG_ELEMENT(stop, SUPPORTS_NONE)
SVG_ELEMENT(style, SUPPORTS_NONE)
SVG_ELEMENT(svg, SUPPORTS_ALL)
SVG_ELEMENT(svgSwitch, SUPPORTS_ALL) 
SVG_ELEMENT(symbol, SUPPORTS_LANG|SUPPORTS_EXTERNAL)
SVG_ELEMENT(text, SUPPORTS_ALL)
SVG_ELEMENT(textPath, SUPPORTS_ALL)
SVG_ELEMENT(title, SUPPORTS_LANG)
SVG_ELEMENT(tref, SUPPORTS_ALL)
SVG_ELEMENT(tspan, SUPPORTS_ALL)
SVG_ELEMENT(use, SUPPORTS_ALL)
SVG_ELEMENT(view, SUPPORTS_EXTERNAL)
SVG_ELEMENT(vkern, SUPPORTS_NONE)
