































































#define ATTRS_NONE        0x00
#define ATTRS_CONDITIONAL 0x01
#define ATTRS_EXTERNAL    0x02
#define ATTRS_ALL         (ATTRS_CONDITIONAL | ATTRS_EXTERNAL)

SVG_ELEMENT(a, ATTRS_ALL)
SVG_ELEMENT(altGlyph, ATTRS_ALL)
SVG_ELEMENT(altGlyphDef, ATTRS_NONE)
SVG_ELEMENT(altGlyphItem, ATTRS_NONE)
SVG_ELEMENT(animate, ATTRS_ALL)
SVG_ELEMENT(animateColor, ATTRS_ALL)
SVG_ELEMENT(animateMotion, ATTRS_ALL)
SVG_ELEMENT(animateTransform, ATTRS_ALL)
SVG_ELEMENT(circle, ATTRS_ALL)
SVG_ELEMENT(clipPath, ATTRS_ALL)
SVG_ELEMENT(colorProfile, ATTRS_NONE)
SVG_ELEMENT(cursor, ATTRS_ALL)
SVG_ELEMENT(definition_src, ATTRS_NONE)
SVG_ELEMENT(defs, ATTRS_ALL)
SVG_ELEMENT(desc, ATTRS_NONE)
SVG_ELEMENT(ellipse, ATTRS_ALL)
SVG_ELEMENT(feBlend, ATTRS_NONE)
SVG_ELEMENT(feColorMatrix, ATTRS_NONE)
SVG_ELEMENT(feComponentTransfer, ATTRS_NONE)
SVG_ELEMENT(feComposite, ATTRS_NONE)
SVG_ELEMENT(feConvolveMatrix, ATTRS_NONE)
SVG_ELEMENT(feDiffuseLighting, ATTRS_NONE)
SVG_ELEMENT(feDisplacementMap, ATTRS_NONE)
SVG_ELEMENT(feDistantLight, ATTRS_NONE)
SVG_ELEMENT(feFlood, ATTRS_NONE)
SVG_ELEMENT(feFuncR, ATTRS_NONE)
SVG_ELEMENT(feFuncG, ATTRS_NONE)
SVG_ELEMENT(feFuncB, ATTRS_NONE)
SVG_ELEMENT(feFuncA, ATTRS_NONE)
SVG_ELEMENT(feGaussianBlur, ATTRS_NONE)
SVG_ELEMENT(feImage, ATTRS_EXTERNAL)
SVG_ELEMENT(feMerge, ATTRS_NONE)
SVG_ELEMENT(feMergeNode, ATTRS_NONE)
SVG_ELEMENT(feMorphology, ATTRS_NONE)
SVG_ELEMENT(feOffset, ATTRS_NONE)
SVG_ELEMENT(fePointLight, ATTRS_NONE)
SVG_ELEMENT(feSpecularLighting, ATTRS_NONE)
SVG_ELEMENT(feSpotLight, ATTRS_NONE)
SVG_ELEMENT(feTile, ATTRS_NONE)
SVG_ELEMENT(feTurbulence, ATTRS_NONE)
SVG_ELEMENT(filter, ATTRS_EXTERNAL)
SVG_ELEMENT(font, ATTRS_EXTERNAL)
SVG_ELEMENT(font_face, ATTRS_NONE)
SVG_ELEMENT(font_face_format, ATTRS_NONE)
SVG_ELEMENT(font_face_name, ATTRS_NONE)
SVG_ELEMENT(font_face_src, ATTRS_NONE)
SVG_ELEMENT(font_face_uri, ATTRS_NONE)
SVG_ELEMENT(foreignObject, ATTRS_ALL)
SVG_ELEMENT(g, ATTRS_ALL)
SVG_ELEMENT(glyph, ATTRS_NONE)
SVG_ELEMENT(glyphRef, ATTRS_NONE)
SVG_ELEMENT(hkern, ATTRS_NONE)
SVG_ELEMENT(image, ATTRS_ALL)
SVG_ELEMENT(line, ATTRS_ALL)
SVG_ELEMENT(linearGradient, ATTRS_EXTERNAL)
SVG_ELEMENT(marker, ATTRS_NONE)
SVG_ELEMENT(mask, ATTRS_ALL)
SVG_ELEMENT(metadata, ATTRS_NONE)
SVG_ELEMENT(missingGlyph, ATTRS_NONE)
SVG_ELEMENT(mpath, ATTRS_EXTERNAL)
SVG_ELEMENT(path, ATTRS_ALL)
SVG_ELEMENT(pattern, ATTRS_ALL)
SVG_ELEMENT(polygon, ATTRS_ALL)
SVG_ELEMENT(polyline, ATTRS_ALL)
SVG_ELEMENT(radialGradient, ATTRS_EXTERNAL)
SVG_ELEMENT(rect, ATTRS_ALL)
SVG_ELEMENT(script, ATTRS_EXTERNAL)
SVG_ELEMENT(set, ATTRS_ALL)
SVG_ELEMENT(stop, ATTRS_NONE)
SVG_ELEMENT(style, ATTRS_NONE)
SVG_ELEMENT(svg, ATTRS_ALL)
SVG_ELEMENT(svgSwitch, ATTRS_ALL) 
SVG_ELEMENT(symbol, ATTRS_NONE)
SVG_ELEMENT(text, ATTRS_ALL)
SVG_ELEMENT(textPath, ATTRS_ALL)
SVG_ELEMENT(title, ATTRS_NONE)
SVG_ELEMENT(tref, ATTRS_ALL)
SVG_ELEMENT(tspan, ATTRS_ALL)
SVG_ELEMENT(use, ATTRS_ALL)
SVG_ELEMENT(view, ATTRS_EXTERNAL)
SVG_ELEMENT(vkern, ATTRS_NONE)
