$inherits:
  from: 'tasks/builds/b2g_flame_kk_nightly_base.yml'
  variables:
    build_name: 'flame-kk'
    build_type: 'opt'
task:
  metadata:
    name: '[TC] B2G Flame KK Nightly (user)'
  workerType: balrog
  scopes:
    - 'docker-worker:cache:build-flame-kk-nightly-user'

  payload:
    cache:
        build-flame-kk-nightly-user: /home/worker/workspace
    env:
      VARIANT: user
