$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
task:
  scopes:
    - 'docker-worker:cache:build-flame-kk-opt'
  metadata:
    name: B2G Flame KK Opt
  payload:
    cache:
      build-flame-kk-opt: /home/worker/object-folder
    env:
      TARGET: 'flame-kk'
      DEBUG: 0
  extra:
    locations:
      img: 'private/build/flame-kk.zip'

