$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'flame-kk-spark-eng'
    build_type: 'opt'
task:
  workerType: flame-kk
  scopes:
    - 'docker-worker:cache:build-flame-kk-spark-eng'
  metadata:
    name: '[TC] B2G Flame KK Eng (spark)'

  payload:
    cache:
      build-flame-kk-spark-eng: /home/worker/workspace
    env:
      TARGET: 'flame-kk'
      DEBUG: 0
      VARIANT: eng
      GAIA_OPTIMIZE: '1'
      B2G_SYSTEM_APPS: '1'
      MOZHARNESS_CONFIG: b2g/taskcluster-spark.py
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone.sh $HOME/workspace
  extra:
    treeherderEnv:
      - staging
    treeherder:
      symbol: Be
      groupSymbol: Flame-KK-spark
      groupName: Flame KitKat Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/flame-kk.zip'
