taskId: {{build_slugid}}
task:
  created: '{{now}}'
  deadline: '{{#from_now}}24 hours{{/from_now}}'
  metadata:
    source: http://todo.com/soon
    owner: {{owner}}
    name: B2G Emulator {{build-type}}
    description: B2G Emulator {{build-type}}

  workerType: b2gbuild
  provisionerId: aws-provisioner

  scopes:
    - 'docker-worker:cache:build-emulator-objects'

  payload:
    cache:
      build-emulator-objects: '/home/worker/object-folder-{{b2g-config}}-{{debug}}'

    env:
      TARGET: 'emulator'
      B2G_CONFIG: '{{b2g-config}}'
      # revision/project params defined originally here https://github.com/taskcluster/taskcluster-try/blob/master/try/instantiate.js
      REVISION: '{{revision}}'
      REPOSITORY: '{{repository}}'

    image: '{{#docker_image}}builder{{/docker_image}}'
    maxRunTime: 7200

    command:
      - build-emulator.sh

    artifacts:
      'public/build':
        type: directory
        path: '/home/worker/artifacts/'
        expires: '{{#from_now}}1 year{{/from_now}}'

  extra:
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/emulator.tar.gz'
      tests: ['public/build/b2g-tests.zip', 'public/build/gaia-tests.zip']
      symbols: 'public/build/b2g-crashreporter-symbols.zip'
      sources: 'public/build/sources.xml'

    treeherder:
      symbol: B
