$inherits:
  from: 'tasks/builds/b2g_desktop_base.yml'
  variables:
    build_type: 'opt'

task:
  scopes:
      - 'docker-worker:cache:workspace-b2g-desktop-objects-opt'

  payload:
    cache:
      workspace-b2g-desktop-objects-opt: '/home/worker/workspace'

    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/nightly'
