$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'flame-kk-nightly'
    build_type: 'opt'
task:
  workerType: flame-kk
  scopes:
    - 'docker-worker:cache:build-flame-kk-nightly'
  metadata:
    name: '[TC] B2G Flame KK Nightly'

  payload:
    cache:
      build-flame-kk-nightly: /home/worker/object-folder
    env:
      TARGET: 'flame-kk'
      DEBUG: 0
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone-nightly.sh $HOME/workspace

  extra:
    treeherder:
      symbol: B
      groupSymbol: Flame-KK
      groupName: Flame KitKat Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/flame-kk.zip'
      mar: 'public/build/b2g-flame-gecko-update.mar'
