$inherits:
  from: 'tasks/builds/b2g_flame_kk_nightly_base.yml'
  variables:
    build_name: 'flame-kk'
    build_type: 'debug'
task:
  metadata:
    name: '[TC] B2G Flame KK Nightly (userdebug)'
  workerType: balrog
  scopes:
    - 'docker-worker:cache:build-flame-kk-nightly-debug'

  payload:
    cache:
        build-flame-kk-nightly-debug: /home/worker/workspace
    env:
      VARIANT: userdebug
      B2G_DEBUG: 0
