$inherits:
  from: 'tasks/builds/b2g_phone_eng_base.yml'
  variables:
    build_name: 'flame-kk-eng-blobfree'
    build_type: 'opt'
task:
  scopes:
    - 'docker-worker:cache:build-flame-kk-eng-blobfree'
  metadata:
    name: 'B2G Flame KK Eng (blobfree)'

  payload:
    cache:
      build-flame-kk-eng-blobfree: /home/worker/workspace
    env:
      TARGET: 'flame-kk'
      MOZHARNESS_CONFIG: b2g/taskcluster-phone-blobfree.py
  extra:
    treeherderEnv:
      - staging
    treeherder:
      symbol: Bef
      groupSymbol: Flame-KK
      groupName: Flame KitKat Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'public/build/flame-kk.zip'
