$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
task:
  scopes:
    - 'docker-worker:cache:build-flame-kk-eng'
  metadata:
    name: B2G Flame KK Eng
  payload:
    cache:
      build-flame-kk-eng: /home/worker/object-folder
    env:
      TARGET: 'flame-kk'
      DEBUG: 0
      VARIANT: eng

