$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'flame-kk-blobfree'
    build_type: 'opt'
task:
  workerType: flame-kk
  scopes:
    - 'docker-worker:cache:build-flame-kk-opt-blobfree'
  metadata:
    name: 'B2G Flame KK Opt (blobfree)'

  payload:
    cache:
      build-flame-kk-opt-blobfree: /home/worker/workspace
    env:
      TARGET: 'flame-kk'
      DEBUG: 0
      MOZHARNESS_CONFIG: b2g/taskcluster-phone-blobfree.py
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone.sh $HOME/workspace
  extra:
    treeherderEnv:
      - staging
    treeherder:
      symbol: Bf
      groupSymbol: Flame-KK
      groupName: Flame KitKat Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'public/build/flame-kk.zip'
