taskId: {{build_slugid}}
task:
  created: '{{now}}'
  deadline: '{{#from_now}}24 hours{{/from_now}}'
  metadata:
    source: http://todo.com/soon
    owner: {{owner}}
    name: B2G Desktop Opt
    description: B2G Desktop Opt

  workerType: b2gbuild
  provisionerId: aws-provisioner

  scopes:
    - 'docker-worker:cache:tc-vcs'
    - 'docker-worker:cache:sources-gecko'
    - 'docker-worker:cache:sources-gaia'
    - 'docker-worker:cache:build-b2g-desktop-objects'
    - 'docker-worker:image:{{#docker_image}}builder{{/docker_image}}'

  payload:
    cache:
      tc-vcs: '/home/worker/.tc-vcs'
      sources-gaia: '/home/worker/gaia'
      sources-gecko: '/home/worker/gecko'
      build-b2g-desktop-objects: '/home/worker/object-folder'

    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/nightly'
      # revision/project params defined originally here https://github.com/taskcluster/taskcluster-try/blob/master/try/instantiate.js
      GECKO_BASE_REPOSITORY: '{{base_repository}}'
      GECKO_HEAD_REPOSITORY: '{{head_repository}}'
      GECKO_HEAD_REV: '{{head_rev}}'
      GECKO_HEAD_REF: '{{head_ref}}'
      MOZTT_GIT_URL: '{{moztt_git_url}}'
      MOZTT_REVISION: '{{moztt_revision}}'

    image: '{{#docker_image}}builder{{/docker_image}}'
    maxRunTime: 3600

    command:
      - bin/build-b2g-desktop.sh

    artifacts:
      'public/build':
        type: directory
        path: '/home/worker/artifacts/'
        expires: '{{#from_now}}1 year{{/from_now}}'

  extra:
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.linux-x86_64.tar.bz2'
      tests: 'public/build/target.tests.zip'

    treeherder:
      symbol: B
