$inherits:
  from: 'tasks/builds/b2g_desktop_base.yml'
  variables:
    build_type: 'debug'

task:
  extra:
    treeherder:
      collection:
        debug: true

  payload:
    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/debug'
