$inherits:
  from: 'tasks/build.yml'
task:
  metadata:
    name: '[TC] Mulet Linux'
    description: Mulet Linux

  workerType: mulet-opt
  scopes:
    - 'docker-worker:cache:build-mulet-linux-workspace'
    - 'docker-worker:cache:tooltool-cache'

  payload:
    cache:
      build-mulet-linux-workspace: '/home/worker/workspace'
      tooltool-cache: '/home/worker/tools/tooltool-cache'

    env:
      MOZCONFIG: 'b2g/dev/config/mozconfigs/linux64/mulet'

    maxRunTime: 3600

    command:
      - /bin/bash
      - -c
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/builder &&
        buildbot_step 'Build' ./build-mulet-linux.sh $HOME/workspace

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      # Disable "TC" prefix...
      groupSymbol: "?"
      machine:
        platform: mulet-linux64
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.linux-x86_64.tar.bz2'
      tests: 'public/build/target.tests.zip'
