<!DOCTYPE window [
<!ENTITY % brandDTD SYSTEM "chrome:
%brandDTD;
<!ENTITY % browserDTD SYSTEM "chrome:
%browserDTD;
<!ENTITY % syncBrandDTD SYSTEM "chrome:
%syncBrandDTD;
<!ENTITY % baseMenuDTD SYSTEM "chrome:
%baseMenuDTD;
<!ENTITY % charsetDTD SYSTEM "chrome:
%charsetDTD;
<!ENTITY % textcontextDTD SYSTEM "chrome:
%textcontextDTD;
<!ENTITY % customizeToolbarDTD SYSTEM "chrome:
  %customizeToolbarDTD;
<!ENTITY % placesDTD SYSTEM "chrome:
%placesDTD;
#ifdef MOZ_SAFE_BROWSING
<!ENTITY % safebrowsingDTD SYSTEM "chrome:
%safebrowsingDTD;
#endif
<!ENTITY % aboutHomeDTD SYSTEM "chrome:
%aboutHomeDTD;
]>

