<!DOCTYPE window [
<!ENTITY % brandDTD SYSTEM "chrome:
%brandDTD;
<!ENTITY % browserDTD SYSTEM "chrome:
%browserDTD;
<!ENTITY % globalDTD SYSTEM "chrome:
%globalDTD;
<!ENTITY % globalRegionDTD SYSTEM "chrome:
%globalRegionDTD;
<!ENTITY % charsetDTD SYSTEM "chrome:
%charsetDTD;
<!ENTITY % textcontextDTD SYSTEM "chrome:
%textcontextDTD;
#ifdef TOOLBAR_CUSTOMIZATION_SHEET
<!ENTITY % customizeToolbarDTD SYSTEM "chrome:
  %customizeToolbarDTD;
#endif
<!ENTITY % placesDTD SYSTEM "chrome:
%placesDTD;
#ifdef MOZ_SAFE_BROWSING
<!ENTITY % safebrowsingDTD SYSTEM "chrome:
%safebrowsingDTD;
#endif
]>

