





"""
Verifies that files generated by two-steps-removed actions are built before
dependent compile steps.
"""

import os
import sys
import TestGyp





test = TestGyp.TestGyp(formats=['ninja'])
test.run_gyp('chained-dependency.gyp')
objext = '.obj' if sys.platform == 'win32' else '.o'
test.build('chained-dependency.gyp',
           os.path.join('obj', 'chained.chained' + objext))

test.pass_test()
