---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/job_flags.yml

$inherits:
  from: tasks/branches/mozilla-central/job_flags.yml

builds:
  flame-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml

tests:
  gaia-ui-test-sanity:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_sanity.yml
  gaia-ui-test-functional:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_functional.yml
  gaia-ui-test-functional-dsds:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_functional_dsds.yml
  gaia-ui-test-unit:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/flame_kk_gaia_ui_test_unit.yml
