# This task is the base for most tests in gecko.
task:
  created: '{{now}}'
  deadline: '{{#from_now}}24 hours{{/from_now}}'
  metadata:
    source: http://todo.com/soon
    owner: mozilla-taskcluster-maintenance@mozilla.com
  tags:
    createdForUser: {{owner}}
  workerType: b2gtest
  provisionerId: aws-provisioner
  schedulerId: task-graph-scheduler

  scopes:
    - 'docker-worker:image:{{#docker_image}}tester{{/docker_image}}'
    - 'queue:define-task:aws-provisioner/test-c4-2xlarge'
    - 'queue:create-task:aws-provisioner/test-c4-2xlarge'

  payload:
    image: '{{#docker_image}}tester{{/docker_image}}'
    maxRunTime: 3600
    env:
      GAIA_HEAD_REPOSITORY: '{{{gaia_head_repository}}}'
      GAIA_BASE_REPOSITORY: '{{{gaia_base_repository}}}'
      GAIA_REF: '{{{gaia_ref}}}'
      GAIA_REV: '{{{gaia_rev}}}'
      MOZHARNESS_REPOSITORY: '{{mozharness_repository}}'
      MOZHARNESS_REV: '{{mozharness_rev}}'

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
