# This task is the base for most tests in gecko.
task:
  created: '{{now}}'
  deadline: '{{#from_now}}24 hours{{/from_now}}'
  metadata:
    source: http://todo.com/soon
    owner: {{owner}}
  workerType: test-c4-2xlarge
  provisionerId: aws-provisioner
  schedulerId: task-graph-scheduler

  scopes:
    - 'docker-worker:image:{{#docker_image}}tester{{/docker_image}}'
    - 'queue:define-task:aws-provisioner/test-c4-2xlarge'
    - 'queue:create-task:aws-provisioner/test-c4-2xlarge'

  payload:
    image: '{{#docker_image}}tester{{/docker_image}}'
    maxRunTime: 3600

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
