



#ifndef SANDBOX_SRC_IPC_TAGS_H__
#define SANDBOX_SRC_IPC_TAGS_H__

namespace sandbox {

enum {
  IPC_UNUSED_TAG = 0,
  IPC_PING1_TAG,  
                  
  IPC_PING2_TAG,  
                  
  IPC_NTCREATEFILE_TAG,
  IPC_NTOPENFILE_TAG,
  IPC_NTQUERYATTRIBUTESFILE_TAG,
  IPC_NTQUERYFULLATTRIBUTESFILE_TAG,
  IPC_NTSETINFO_RENAME_TAG,
  IPC_CREATENAMEDPIPEW_TAG,
  IPC_NTOPENTHREAD_TAG,
  IPC_NTOPENPROCESS_TAG,
  IPC_NTOPENPROCESSTOKEN_TAG,
  IPC_NTOPENPROCESSTOKENEX_TAG,
  IPC_CREATEPROCESSW_TAG,
  IPC_CREATEEVENT_TAG,
  IPC_OPENEVENT_TAG,
  IPC_NTCREATEKEY_TAG,
  IPC_NTOPENKEY_TAG,
  IPC_DUPLICATEHANDLEPROXY_TAG,
  IPC_GDI_GDIDLLINITIALIZE_TAG,
  IPC_GDI_GETSTOCKOBJECT_TAG,
  IPC_USER_REGISTERCLASSW_TAG,
  IPC_LAST_TAG
};

}  

#endif  
